name = "auto-cert-api"
main = "src/index.ts"
compatibility_date = "2026-05-08"

[vars]
R2_KEY_PREFIX = "auto-cert"
CORS_ORIGINS = "*"

[[d1_databases]]
binding = "DB"
database_name = "auto-cert"
database_id = "627a01cf-9744-4ff0-902b-14df7f8a282b"

[[r2_buckets]]
binding = "CERT_BUCKET"
bucket_name = "auto-cert"

[[workflows]]
name = "auto-cert-certificate-workflow"
binding = "CERTIFICATE_WORKFLOW"
class_name = "CertificateWorkflow"
